---
- name: Deploy Calculator Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"

- name: Deploy Calculator Service Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yaml.j2') | from_yaml }}"

- name: Deploy Calculator HPA
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'hpa.yaml.j2') | from_yaml }}"