services:
  api-gateway:
    build: 
      context: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_SERVICE_URL=http://frontend-service:5001
      - CALCULATOR_SERVICE_URL=http://calculator-service:5002
    depends_on:
      - frontend-service
      - calculator-service
    networks:
      - inksight-network

  frontend-service:
    build: 
      context: ./frontend-service
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - CALCULATOR_SERVICE_URL=http://calculator-service:5002
    volumes:
      - ./frontend-service/static:/app/static
      - ./frontend-service/templates:/app/templates
    networks:
      - inksight-network

  calculator-service:
    build: 
      context: ./calculator-service
    environment:
      - FLASK_APP=app.py
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - inksight-network

networks:
  inksight-network:
    driver: bridge