services:
  frontend-service:
    build: 
      context: ./frontend-service
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - CALCULATOR_SERVICE_URL=http://calculator-service:5002
      - DOCUMENT_SERVICE_URL=http://document-service:5003
    volumes:
      - ./frontend-service/static:/app/static
      - ./frontend-service/templates:/app/templates
    ports:
      - "5001:5001"

  calculator-service:
    build: 
      context: ./calculator-service
    environment:
      - FLASK_APP=app.py
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "5002:5002"

  document-service:
    build: 
      context: ./document-service
    env_file:
      - ./.env    # This points to the .env file in the root directory
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "5003:5003"

networks:
  default:
    driver: bridge