# docker-compose.yml
services:
  api-gateway:
    build: 
      context: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_SERVICE_URL=http://frontend-service:5001
      - CALCULATOR_SERVICE_URL=http://calculator-service:5002
      - DOCUMENT_SERVICE_URL=http://document-service:5003
      - AUTH_SERVICE_URL=http://auth-service:5001
    depends_on:
      - frontend-service
      - calculator-service
      - document-service
      - auth-service
    networks:
      - inksight-network

  auth-service:
    build: 
      context: ./auth-service
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    networks:
      - inksight-network

  calculator-service:
    build: 
      context: ./calculator-service
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - inksight-network

  document-service:
    build: 
      context: ./document-service
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - inksight-network

  frontend-service:
    build: 
      context: ./frontend-service
    volumes:
      - ./frontend-service/static:/app/static
      - ./frontend-service/templates:/app/templates
    networks:
      - inksight-network

networks:
  inksight-network:
    driver: bridge
