services:
  api-gateway:
    build: 
      context: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_SERVICE_URL=http://frontend-service:5001
      - CALCULATOR_SERVICE_URL=http://calculator-service:5002
      - DOCUMENT_SERVICE_URL=http://document-service:5003
    depends_on:
      - frontend-service
      - calculator-service
      - document-service
    networks:
      - inksight-network

  frontend-service:
    ports:
      - "5001:5001" 
    build: 
      context: ./frontend-service
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - CALCULATOR_SERVICE_URL=http://calculator-service:5002
      - DOCUMENT_SERVICE_URL=http://document-service:5003
    volumes:
      - ./frontend-service/static:/app/static
      - ./frontend-service/templates:/app/templates
    depends_on:
      - document-service
    networks:
      - inksight-network

  calculator-service:
    ports:
      - "5002:5002"
    build: 
      context: ./calculator-service
    environment:
      - FLASK_APP=app.py
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - inksight-network

  document-service:
    ports:
      - "5003:5003"
    build:
      context: ./document-service
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OAUTHLIB_INSECURE_TRANSPORT=1
    volumes:
      - type: bind
        source: ./credentials.json
        target: /app/credentials.json
        read_only: true
    networks:
      - inksight-network

networks:
  inksight-network:
    driver: bridge