apiVersion: v1
kind: Secret
metadata:
  name: inksight-secrets
  namespace: inksight
type: Opaque
data:
  GEMINI_API_KEY: QUl6YVN5QVpnWkR0cDZmU0o3Y2NiMkk3U0lhMkU5UjZBR0pZNzMw
  ANTHROPIC_API_KEY: c2stYW50LWFwaDAzLVRLX3FHZ1lrYUdFa0RYVkxvTGJLV3FpMHdPVE5CODFIb29CYVBuRkJaYmFfZzJmR2xxdUdZeGU4YmotVWV6RE13V0FST1ZTdWhMZ0FGazRkQWhEbFNRLVZqc0FYUUFB
  SECRET_KEY: MTIz