apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: inksight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document
        image: devz19/inksight-document:latest
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - secretRef:
            name: inksight-secrets