apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: inksight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        fluentd.org/parser: json  # Tells Fluentd to parse logs as JSON
        fluentd.org/tag: "inksight.calculator"  # Adds custom tag for filtering logs
    spec:
      containers:
      - name: frontend
        image: devz19/inksight-frontend:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: inksight-config
                        # Add logging configuration
        - name: PYTHONUNBUFFERED
          value: "1"  # Ensures Python logs are output immediately
        - name: FLASK_ENV
          value: "production"