# k8/ingress/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inksight-ingress
  namespace: inksight
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:      # No host specified since we're running locally
      paths:
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 5000
      - path: /calculate/?(.*)
        pathType: Prefix
        backend:
          service:
            name: calculator-service
            port:
              number: 5002
      - path: /document/?(.*)
        pathType: Prefix
        backend:
          service:
            name: document-service
            port:
              number: 5003
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 5001