apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-service
  namespace: inksight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-service
  template:
    metadata:
      labels:
        app: calculator-service
    spec:
      containers:
      - name: calculator
        image: devz19/inksight-calculator:latest
        ports:
        - containerPort: 5002
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: GEMINI_API_KEY
          value: "AIzaSyAZgZDtp6fSJ7ccb2I7SIa2E9R6AGJY730"