apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-service
  template:
    metadata:
      labels:
        app: calculator-service
    spec:
      containers:
      - name: calculator-service
        image: inksight/calculator-service:latest
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 5002
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: inksight-secrets
              key: gemini-api-key
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10