apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: frontend-service
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app: calculator-service
---
apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: document-service