apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: inksight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        fluentd.org/parser: json  # Tells Fluentd to parse logs as JSON
        fluentd.org/tag: "inksight.calculator"  # Adds custom tag for filtering logs
    spec:
      containers:
      - name: api-gateway
        image: devz19/inksight-api-gateway:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: inksight-config
        - secretRef:
            name: inksight-secrets
                # Add logging configuration
        env:  # Define individual environment variables here
        - name: PYTHONUNBUFFERED
          value: "1"  # Ensures Python logs are output immediately
        - name: FLASK_ENV
          value: "production"
